### PR TITLE
Update spin version to 5.0

### PR DESCRIPTION
**Pull request by rafalmiel**
Also remove pointer_method feature which is now stable

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks! Could replace the `0.5.*` wildcard with `0.5.0` for consistency? Cargo interprets `0.5.0` as `^0.5.0`, so it is equivalent to the wildcard here (and wildcards are generally discouraged because they also allows cargo to select very early versions).

**Comment by rafalmiel** [comment]
> Thanks! Could replace the `0.5.*` wildcard with `0.5.0` for consistency? Cargo interprets `0.5.0` as `^0.5.0`, so it is equivalent to the wildcard here (and wildcards are generally discouraged because they also allows cargo to select very early versions).

Yes makes sense, updated the PR. Thanks

**Comment by phil-opp** [comment]
Thanks!

**Comment by phil-opp** [comment]
Released as version 0.6.4

**Pull request merged**
