### PR TITLE
merge front/back padding after allocate current hole

### LINKED ISSUE #53: Merge padding inside global allocate_first_fit
I found that in function [HoleList::allocate_first_fit](https://github.com/phil-opp/linked-list-allocator/blob/master/src/hole.rs#L92), it will call the global allocate_first_fit.
The global `allocate_first_fit` will search and call `split_hole` to get the allocated memory, also generating `front_padding` and `back_padding` to cope with align problem.
However the two padding are merged by `deallocate` in `HoleList::allocate_first_fit` which seems less efficient. Since `deallocate` need to search for the previous holes of two padding, which means it has to go through the linked-list again all over.
In global allocate_first_fit after it call split_hole, it already get the previous hole that can merge the front padding and back padding. I think it will be more efficient to merge padding in global `allocate_first_fit`.

Please correct me if there are anything wrong.

### PR DESCRIPTION
**Pull request by yodalee**
When we allocate a memory chunk, there may be some memory paddings
in front/back of the allocated chunk. Before this change, these paddings
are dealed by calling function deallocate.
However the implementation is inefficient since deallocate function will
search from the beginning of the linked-list and find the right place to
insert these paddings.
With this change, the paddings are linked to linked-list right after
they are generated. We don't have to deal with merge continuous since
paddings are guaranteed to be separated between them and to previous and
next holes.

Fixes #53

### CODE REVIEW

**Review by phil-opp — APPROVED** [review]
Thanks a lot for the PR and sorry for the late review. Looks good to me!

Unfortunately I missed the time window to approve the CI run, which is required by GitHub because this is your first contribution here. Could you push some dummy update to this PR (e.g. an empty commit or a no-op rebase) so that we retry this? Please ping me when you do.

**Comment by yodalee** [comment]
@phil-opp 
Done. I use rebase/reword to change the commit. It is updated now.

**Comment by phil-opp** [comment]
Thanks a lot! Looks like there is a minor rustfmt issue, otherwise this seems good to go

**Comment by phil-opp** [comment]
I'll publish this together with #55 as soon as its merged.

**Pull request merged**
