### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Mradul-Hub**

### CODE REVIEW

**Comment by phil-opp** [comment]
This seems like an accidental pull request, given that this adds an unrelated C file?

**Comment by phil-opp** [comment]
Looking at your activity, it appears that you opened a lot of such invalid pull requests against different repositories yesterday. If you do this to complete the hacktoberfest challenge, this is not how you should do it. You're only creating noise and spamming maintainers this way and you will likely be reported to GitHub.

**Comment by robert-w-gries** [comment]
This is frustrating. @phil-opp I'll help keep an eye on invalid PRs in the rust-os-dev group. Hope it lessens your burden!

**Comment by phil-opp** [comment]
@robert-w-gries Thanks a lot for your help! I don't expect that we'll have a large problem with this since OS development in Rust is a rather niche topic. My guess is that this crate just came up in a search for "linked list".

**Pull request closed without merging**
