### PR TITLE
Update to new nightly API

### PR DESCRIPTION
**Pull request by jackpot51**

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks! Unfortunately I'm on vacation right now, so I can't push a new version to crates.io yet (or is there an easy way to do it from mobile?).

**Comment by jackpot51** [comment]
No easy way to do it. This is a breaking change for people with older nightlies so it is probably ok it waits until you come back

**Comment by jackpot51** [comment]
Those of us on the latest nightly can use git source

**Comment by phil-opp** [comment]
Published as version 0.4.2.

**Pull request merged**
